repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          ["--profile", "black", "--filter-files", "--skip-glob=__init__.py"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: local
    hooks:
      - id: pre-commit-script
        name: pre-commit script
        entry: ./pre-commit-checks.sh
        language: script
