[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hitchhiker"
version = "0.0.1"
description = ""
requires-python = ">=3.7"
dependencies = [
    "click>=8,<9",
    "tomlkit>=0.12.0,<1",
    "dotty-dict>=1.3.1,<2",
]

[project.scripts]
hitchhiker = "hitchhiker.cli:cli.cli"

[project.optional-dependencies]
release = [
    "PyGithub>=1.59.1,<2",
    "gitpython>=3.1.32,<4",
]
odoo = [
    "click-odoo>=1.6,<2",
]
test = [
    "pytest>=7,<8",
]
copier = [
    "copier>=8.3.0,<9",
]

[tool.pytest.ini_options]
python_files = ["tests/*.py", "tests/**/*.py"]

[tool.pylint.'MESSAGES CONTROL']
disable = "C0114, C0301"
