name: Build & Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install coverage
          python setup.py egg_info
          pip install `grep -v '^\[' *.egg-info/requires.txt`
      - name: Test with pytest and generate coverage report
        run: |
          coverage run --source . -m pytest -vv --tb=long
          coverage xml -o coverage.xml
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  test-no-optional-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Install
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest -vv --tb=long
      - name: Run
        run: |
          hitchhiker --help

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python setup.py egg_info
          pip install `grep -v '^\[' *.egg-info/requires.txt`
      - name: Type check with mypy
        run: mypy --install-types --non-interactive ./hitchhiker --strict --no-warn-unused-ignores
